idscea/urls.py
import django.contrib.auth.views as auth_views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView

from accounts.views import UserRegistrationView
from becas.views import (ConstanciaPdfView, DashboardView, EsePdfView,
                         SocioEconomicStudyUpdate, SocioEconomicStudyView,
                         SolicitudPdfView, StudentAcademicProgramUpdate,
                         StudentAcademicProgramView, StudentProfile,
                         StudentProfileUpdate,
                         UpdateSocioEconomicStudyRedirectView,
                         UpdateStudentAcademicProgramRedirectView,
                         UpdateStudentRedirectView, load_programs)
from convocatoria.views import ConvocatoriasView, aspirante_create
from enlaces.views import (DashboardEnlacesView, ProgramsCreate,
                           ProgramsDelete, ProgramsList, ProgramsUpdate,
                           StudentsValidationDetail, StudentsValidationList,
                           BeneficiariosList)

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^$", TemplateView.as_view(template_name="home.html"), name="home"),
    url(r"^new-user/$", UserRegistrationView.as_view(), name="user_registration"),
    path(
        "register/done/",
        TemplateView.as_view(template_name="register_done.html"),
        name="register_done",
    ),
    url(
        r"^login/$",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    url(r"^logout/$", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    url(
        r"^password_change/$",
        auth_views.PasswordChangeView.as_view(
            template_name="password_change_form.html"
        ),
        name="password_change",
    ),
    url(
        r"password_change/done/$",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("dashboard/", login_required(DashboardView.as_view()), name="dashboard"),
    path(
        "convocatorias/",
        login_required(ConvocatoriasView.as_view()),
        name="convocatorias",
    ),
    url(
        r"convocatorias/(?P<convocCode>[a-zA-Z0-9]+)/$",
        login_required(aspirante_create),
        name="create-aspirante",
    ),
    path("profile/", login_required(StudentProfile.as_view()), name="student-profile"),
    url(
        r"profile/(?P<pk>\d+)/update/$",
        login_required(StudentProfileUpdate.as_view()),
        name="student-profile-update",
    ),
    path(
        "profile/redirect",
        login_required(UpdateStudentRedirectView.as_view()),
        name="student-profile-redirect",
    ),
    path(
        "economic/",
        login_required(SocioEconomicStudyView.as_view()),
        name="socio-economic-study",
    ),
    url(
        r"economic/(?P<pk>\d+)/update/$",
        login_required(SocioEconomicStudyUpdate.as_view()),
        name="socio-economic-study-update",
    ),
    path(
        "economic/redirect",
        login_required(UpdateSocioEconomicStudyRedirectView.as_view()),
        name="socio-economic-study-redirect",
    ),
    path(
        "academic/",
        login_required(StudentAcademicProgramView.as_view()),
        name="academic-program",
    ),
    url(
        r"academic/(?P<pk>\d+)/update/$",
        login_required(StudentAcademicProgramUpdate.as_view()),
        name="academic-program-update",
    ),
    path(
        "academic/redirect",
        login_required(UpdateStudentAcademicProgramRedirectView.as_view()),
        name="academic-program-redirect",
    ),
    path("ajax/load-programs/", load_programs, name="ajax-load-programs"),
    path(
        "enlaces/",
        login_required(DashboardEnlacesView.as_view()),
        name="dashboard-enlaces",
    ),
    path(
        "enlaces/programs/list",
        login_required(ProgramsList.as_view()),
        name="programs-list",
    ),
    url(
        r"programs/(?P<pk>\d+)/update/$",
        login_required(ProgramsUpdate.as_view()),
        name="programs-update",
    ),
    path(
        "enlaces/programs/create",
        login_required(ProgramsCreate.as_view()),
        name="programs-create",
    ),
    path(
        "enlaces/programs/delete/<str:username>",
        login_required(ProgramsDelete.as_view()),
        name="programs-delete",
    ),
    path(
        "enlaces/student_validation",
        login_required(StudentsValidationList.as_view()),
        name="student-validation",
    ),
    path(
        "enlaces/aspirant/<int:pk>",
        login_required(StudentsValidationDetail.as_view()),
        name="aspirant-view",
    ),
    path(
        "generate_constancia/", ConstanciaPdfView.as_view(), name="constancia-print-pdf"
    ),
    path("generate_solicitud/", SolicitudPdfView.as_view(), name="solicitud-print-pdf"),
    path("generate_ese/", EsePdfView.as_view(), name="ese-print-pdf"),
    path("beneficiarios/", BeneficiariosList.as_view(), name="beneficiarios"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

becas/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.core.validators import (MaxValueValidator, MinValueValidator,
                                    RegexValidator)
from django.db import models
from PIL import Image


def path_and_rename(instance, filename):
    upload_to = "photos"
    ext = filename.split(".")[-1]
    # set filename as random string
    filename = "{}.{}".format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Estados(models.Model):
    estado_id = models.AutoField(primary_key=True)
    estado = models.CharField("Estado", max_length=150)

    def __str__(self):
        return "%s" % self.estado


class Municipios(models.Model):
    municipio_id = models.AutoField(primary_key=True)
    municipio = models.CharField("Municipio", max_length=150)

    def __str__(self):
        return "%s" % self.municipio


class MaritalStatus(models.Model):
    """Estado civil"""

    marital_status_id = models.AutoField(primary_key=True)
    marital_status = models.CharField(
        "Estado Civil",
        max_length=150,
    )

    def __str__(self):
        return "%s" % self.marital_status


class Student(models.Model):
    """Información personal"""

    username = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        editable=False,
        primary_key=True,
    )
    student_id = models.CharField(
        "Número de identifcación del estudiante", max_length=25
    )
    nombre = models.CharField("Nombre(s)", max_length=25)
    primer_apellido = models.CharField("Apellido paterno", max_length=15)
    segundo_apellido = models.CharField("Apellido materno", max_length=15)
    fecha_nacimiento = models.DateField("Fecha de nacimiento")
    lugar_nacimiento = models.ForeignKey(
        to=Estados,
        on_delete=models.CASCADE,
        verbose_name="Lugar de nacimiento",
    )
    ine = models.CharField(
        "INE",
        max_length=13,
        null=True,
        blank=True,
        help_text='Registra los 13 digitos que siguen a los simbolos "<<" en la parte posterior de tu INE.',
        validators=[
            RegexValidator(
                regex=r"([0-9]{13})",
                message="Ingresa una clave INE válida.",
                code="invalid_ine",
            )
        ],
    )
    marital_status = models.ForeignKey(
        to=MaritalStatus,
        on_delete=models.CASCADE,
        verbose_name="Estado civil",
    )

    """Datos de contacto"""
    calle = models.CharField("Calle", max_length=100)
    numero_ext = models.IntegerField("Número exterior")
    numero_int = models.IntegerField("Número interior", null=True, blank=True)
    colonia = models.CharField("Colonia", max_length=100)
    cp = models.IntegerField(
        "Código postal",
        validators=[MinValueValidator(20000), MaxValueValidator(20999)],
    )
    localidad = models.CharField("Localidad", max_length=100)
    municipio = models.ForeignKey(
        to=Municipios,
        on_delete=models.CASCADE,
        verbose_name="Municipio",
    )
    telefono = models.CharField(
        "Teléfono fijo",
        max_length=10,
        validators=[
            RegexValidator(
                regex=r"([0-9]{10})",
                message="Ingresa un teléfono válido de 10 dígitos.",
                code="invalid_phone",
            )
        ],
    )
    celular = models.CharField(
        "Celular",
        max_length=10,
        validators=[
            RegexValidator(
                regex=r"([0-9]{10})",
                message="Ingresa un teléfono válido de 10 digitos.",
                code="invalid_phone",
            )
        ],
    )
    validated = models.BooleanField(default=False)
    pic = models.ImageField(
        "Foto de perfil",
        upload_to=path_and_rename,
        null=False,
        blank=False,
        help_text="Esta fotografía se imprimira en la solicitud y expendiente. Se requiere fotografía tipo pasaporte.",
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.pic.path)
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.pic.path)

    def __str__(self):
        return "%s" % self.username


class Universities(models.Model):

    university_id = models.AutoField(primary_key=True)
    university = models.CharField("Universidad", max_length=150)

    def __str__(self):
        return "%s" % self.university


class Modalidades(models.Model):

    modalidad_id = models.AutoField(primary_key=True)
    modalidad = models.CharField("Modalidad", max_length=150)

    def __str__(self):
        return "%s" % self.modalidad


class Grados(models.Model):
    grado_id = models.AutoField(primary_key=True)
    grado = models.CharField("Modalidad", max_length=150)

    def __str__(self):
        return "%s" % self.grado


class Programs(models.Model):
    program_id = models.AutoField(primary_key=True)
    university = models.ForeignKey(
        to=Universities,
        on_delete=models.CASCADE,
        verbose_name="Universidad",
    )
    grado = models.ForeignKey(
        to=Grados,
        on_delete=models.CASCADE,
        verbose_name="Grado",
    )
    modalidad = models.ForeignKey(
        to=Modalidades,
        on_delete=models.CASCADE,
        verbose_name="Modalidad",
    )
    programa = models.CharField("Programa", max_length=128)
    duracion = models.IntegerField("Duración (semestres/cuatrimestres)")
    costo = models.IntegerField("Costo por semestre/cuatrimestre")

    def __str__(self):
        return "%s - %s" % (self.university, self.programa)


class StudentAcademicProgram(models.Model):
    username = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        editable=False,
        primary_key=True,
    )
    university = models.ForeignKey(
        to=Universities,
        on_delete=models.CASCADE,
        verbose_name="Universidad",
    )
    grado = models.ForeignKey(
        to=Grados,
        on_delete=models.CASCADE,
        verbose_name="Grado",
    )
    continua = models.BooleanField(
        "En caso de TSU, planeo continuar con mis estudios a nivel licenciatura o ingeniería.",
        max_length=150,
    )
    programa = models.ForeignKey(
        to=Programs,
        on_delete=models.CASCADE,
        verbose_name="Programa",
    )
    nivel_actual = models.PositiveSmallIntegerField("Semestre/Cuatrimestre actual")
    promedio = models.FloatField(
        "Promedio general",
        validators=[
            MaxValueValidator(10, "Ingrese un promedio valido (menor a 10)."),
            MinValueValidator(8.5, "Ingrese un promedio valido (mayor a 8.5)."),
        ],
    )
    validated = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % self.username


############################################################################################################
#                                        Estudio Socio Económico                                           #
############################################################################################################


class PovertyRange(models.Model):
    """Rangos de pobreza de acuerdo con CONEVAL"""

    poverty_id = models.AutoField(primary_key=True)
    poverty = models.CharField(
        "Rango de pobreza de su colonia",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.poverty


class AverageGradeRanges(models.Model):
    """Rangos de promedio general"""

    average_grade_range_id = models.AutoField(primary_key=True)
    average_grade_range = models.CharField(
        "Promedio general",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.average_grade_range


class FamilyMembersRange(models.Model):
    """Rangos de integrantes de familia"""

    family_members_range_id = models.AutoField(primary_key=True)
    family_members_range = models.CharField(
        "Número de integrantes de la familia",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.family_members_range


class FamilyMonthlyIncome(models.Model):
    """Ingresos familiares"""

    family_monthly_income_id = models.AutoField(primary_key=True)
    family_monthly_income = models.CharField(
        "Ingreso familiar mensual",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.family_monthly_income


class ParentsEducationLevel(models.Model):
    """Ingresos familiares"""

    parent_education_level_id = models.AutoField(primary_key=True)
    parent_education_level = models.CharField(
        "Nivel educativo del padre/madre",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.parent_education_level


class SocialSecurity(models.Model):
    """Seguridad social"""

    social_security_id = models.AutoField(primary_key=True)
    social_security = models.CharField(
        "Afiliación a servicios de salud y seguridad social",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.social_security


class ProviderPerks(models.Model):
    """Seguridad social"""

    provider_perks_id = models.AutoField(primary_key=True)
    provider_perks = models.CharField(
        "Principal proveedor con prestaciones",
        max_length=150,
    )
    value = models.IntegerField("Puntuación")

    def __str__(self):
        return "%s" % self.provider_perks


class HomeType(models.Model):

becas/templates/academic_program.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    {% include "sub_menu.html" %}

    <div class="container">
        <div class="row justify-content-md-center mt-4" style="background-color:white;">
            <div class="col col-lg">
                <br><h2>Recomendaciones de llenado</h2><br>
                <p class="lead" align="justify">Antes de comenzar con el llenado de la solicitud para aplicar al apoyo de la beca, es necesario que cuentes con toda la información requerida de forma precisa y completa.
                    La aplicación podrá ser guardada y actualizada posteriormente si fuera necesario.
                Es posible ingresar los datos desde tu celular. Sin embargo, te recomendamos utilizar una computadora de escritorio o una laptop.</p><br>
                <h2>Información académica</h2>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-md-center" style="background-color:white;">
            <div class="col col-lg">

                <form method="POST" action="" id="academicProgramForm"
                      academic-programs-url="{% url 'ajax-load-programs' %}">
                    {% csrf_token %}
                    {% crispy form %}
                </form>

            </div>
        </div>
    </div>

    <script>

        var url = $("#academicProgramForm").attr("academic-programs-url");

        if (document.getElementById("id_university").selectedIndex == 0 && document.getElementById("id_grado").selectedIndex == 0) {
            $("#id_programa").html("<option value=\"\">---------</option>");
        }

        if (document.getElementById("id_university").selectedIndex != 0 && document.getElementById("id_grado").selectedIndex != 0) {
            var programaId = $("#id_programa").val();
            var universityId = $("#id_university").val();
            var gradoId = $("#id_grado").val();
            $.ajax({
                url: url,
                data: {
                    'university_id': universityId,
                    'grado_id': gradoId
                },
                success: function (data) {
                    $("#id_programa").html(data);
                    $("#id_programa option[value='" + programaId + "']").attr("selected", true);
                }
            });
        }

        $("#id_university").change(function () {
            var universityId = $("#id_university").val();
            var gradoId = $("#id_grado").val();
            $.ajax({
                url: url,
                data: {
                    'university_id': universityId,
                    'grado_id': gradoId
                },
                success: function (data) {
                    console.log(data);
                    $("#id_programa").html(data);
                }
            });
        });

        $("#id_grado").change(function () {
            var universityId = $("#id_university").val();
            var gradoId = $("#id_grado").val();
            $.ajax({
                url: url,
                data: {
                    'university_id': universityId,
                    'grado_id': gradoId
                },
                success: function (data) {
                    $("#id_programa").html(data);
                }
            });
        });
    </script>
{% endblock %}

becas/templates/constancia.html
{% load humanize %}
{% load static %}

<!DOCTYPE html>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" rel="stylesheet">
    </head>

    <body lang=ES-MX style='tab-interval:35.4pt;word-wrap:break-word'>

    <div class=WordSection1>

    <p class=MsoNormal align=center style='text-align:center'><b style='mso-bidi-font-weight:
    normal'><span style='font-size:12.0pt;line-height:115%'>CONSTANCIA DE
    PARTICIPACI&Oacute;N PARA D&Eacute;CIMA CONVOCATORIA DE BECA FIBEIPES<o:p></o:p></span></b></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'>A quien
    corresponda:</p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'>La(El) que
    suscribe <span class=GramE><span style='font-size:10.0pt;font-family:"Arial",sans-serif'>Jefa(e)</span></span><span
    style='font-size:10.0pt;font-family:"Arial",sans-serif'> del Departamento de
    Servicios Escolares</span>, hace constar que:</p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><o:p>&nbsp;</o:p></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><b>{{ student.primer_apellido|upper }} {{ student.segundo_apellido|upper }} {{ student.nombre|upper }}</b> es alumna(o) regular del(de la) {{ academic.universidad|upper }} estando inscrito(a) sin adeudo de materias en el semestre n&uacute;mero
    {{ academic.semestre }} de la carrera <b>{{ academic.programa|upper }} en modalidad {{ academic.programa.modalidad|lower }}</b>.</b> </p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><o:p>&nbsp;</o:p></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><o:p>&nbsp;</o:p></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><b
    style='mso-bidi-font-weight:normal'>INFORMACI&Oacute;N GENERAL:<o:p></o:p></b></p>

    <table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
     style='border-collapse:collapse;border:none;mso-border-alt:solid windowtext .5pt;
     mso-yfti-tbllook:1184;mso-padding-alt:0cm 5.4pt 0cm 5.4pt'>
     <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
      <td width=295 valign=top style='width:221.6pt;border:solid windowtext 1.0pt;
      mso-border-alt:solid windowtext .5pt;background:#E7E6E6;mso-background-themecolor:
      background2;padding:0cm 5.4pt 0cm 5.4pt'>
      <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt'><o:p>&nbsp;</o:p></span></b></p>
      </td>
      <td width=293 valign=top style='width:219.8pt;border:solid windowtext 1.0pt;
      border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
      solid windowtext .5pt;background:#E7E6E6;mso-background-themecolor:background2;
      padding:0cm 5.4pt 0cm 5.4pt'>
      <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt;color:black;mso-color-alt:windowtext'>Promedio</span></b><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt'><o:p></o:p></span></b></p>
      </td>
     </tr>
     <tr style='mso-yfti-irow:1;height:35.25pt'>
      <td width=295 valign=top style='width:221.6pt;border:solid windowtext 1.0pt;
      border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
      padding:0cm 5.4pt 0cm 5.4pt;height:35.25pt'>
      <p class=MsoNormal style='text-align:justify;line-height:normal'><span
      style='font-size:9.0pt;mso-bidi-font-size:11.0pt'>4.- Especifique promedio
      inmediato anterior. (En caso de ser de nuevo ingreso, especifique el promedio
      general de bachillerato)<o:p></o:p></span></p>
      </td>
      <td width=293 valign=top style='width:219.8pt;border-top:none;border-left:
      none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
      mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
      mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:35.25pt'>
      <p class=MsoNormal style='line-height:normal;tab-stops:94.45pt center 104.5pt'><span
      style='font-size:9.0pt;mso-bidi-font-size:11.0pt'><span style='mso-tab-count:
      1'> </span>{{ academic.promedio }}<o:p></o:p></span></p>
      </td>
     </tr>
     <tr style='mso-yfti-irow:2'>
      <td width=295 valign=top style='width:221.6pt;border:solid windowtext 1.0pt;
      border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
      background:#E7E6E6;mso-background-themecolor:background2;padding:0cm 5.4pt 0cm 5.4pt'>
      <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt'><o:p>&nbsp;</o:p></span></b></p>
      </td>
      <td width=293 valign=top style='width:219.8pt;border-top:none;border-left:
      none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
      mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
      mso-border-alt:solid windowtext .5pt;background:#E7E6E6;mso-background-themecolor:
      background2;padding:0cm 5.4pt 0cm 5.4pt'>
      <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt;color:black;mso-color-alt:windowtext'>Colegiatura</span></b><b
      style='mso-bidi-font-weight:normal'><span style='font-size:9.0pt;mso-bidi-font-size:
      11.0pt'><o:p></o:p></span></b></p>
      </td>
     </tr>
     <tr style='mso-yfti-irow:3;mso-yfti-lastrow:yes;height:17.8pt'>
      <td width=295 valign=top style='width:221.6pt;border:solid windowtext 1.0pt;
      border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
      padding:0cm 5.4pt 0cm 5.4pt;height:17.8pt'>
      <p class=MsoNormal style='text-align:justify;line-height:normal'><span
      style='font-size:9.0pt;mso-bidi-font-size:11.0pt'>5.-Monto de la Colegiatura
      mensual:<o:p></o:p></span></p>
      </td>
      <td width=293 valign=top style='width:219.8pt;border-top:none;border-left:
      none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
      mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
      mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:17.8pt'>
      <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
      style='font-size:9.0pt;mso-bidi-font-size:11.0pt'>${{ academic.programa.costo|intcomma }}<o:p></o:p></span></p>
      </td>
     </tr>
    </table>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><span
    style='font-size:5.0pt;mso-bidi-font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><span
    style='font-size:5.0pt;mso-bidi-font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><span
    style='font-size:5.0pt;mso-bidi-font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><span
    style='font-size:5.0pt;mso-bidi-font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'>Para los fines
    legales al que el interesado(a) convengan se extiende la presente constancia en
    Aguascalientes, Aguascalientes, {% now "SHORT_DATETIME_FORMAT" %}</b>.</p>

    <p class=MsoNormal style='text-align:justify;line-height:normal'><o:p>&nbsp;</o:p></p>

    <p class=MsoNormal align=center style='text-align:center;line-height:normal'>Atentamente</p>

    <p class=MsoNormal align=center style='text-align:center;line-height:normal'><o:p>&nbsp;</o:p></p>

    <p class=MsoNormal align=center style='text-align:center;line-height:normal'>____________________________</p>

    <p class=MsoNormal align=center style='text-align:center'><b style='mso-bidi-font-weight:
    normal'>Responsable de la Instituci&oacute;n<o:p></o:p></b></p>

    </div>

    </body>

    </html>

becas/templates/student_profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    {% include "sub_menu.html" %}

    <div class="container">
        <div class="row justify-content-md-center mt-4" style="background-color:white;">
            <div class="col col-lg">
                <h2>Perfil</h2>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-md-center" style="background-color:white;">
            <div class="col col-lg">

                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy form %}
                </form>

            </div>
        </div>
    </div>


{% endblock %}